-- Seed data for portfolio development
-- This file runs automatically after migrations during db reset
-- Generated on 2025-12-02T01:21:41.122Z
-- Projects: 11, Sections: 49

-- Insert projects
INSERT INTO projects (id, title, description, company, technologies, responsibilities, challenges, solutions, categories, outcomes, image_urls) VALUES 
(
  '550e8400-e29b-41d4-a716-446655440001',
  'Project One',
  'This is a comprehensive project showcasing modern web development practices with React and cutting-edge technologies. The project demonstrates full-stack development capabilities with a focus on user experience and performance optimization.',
  'Tech Corp',
  ARRAY['React', 'JavaScript', 'CSS', 'Node.js'],
  ARRAY['Frontend Development', 'UI/UX Design', 'Performance Optimization'],
  ARRAY['Complex state management', 'Cross-browser compatibility', 'Performance under load'],
  ARRAY['Implemented Redux for state management', 'Used progressive enhancement', 'Added caching layers'],
  ARRAY['Web Development', 'Frontend'],
  '[{"value":"40%","metric":"Performance","description":"Improvement in page load speed"},{"value":"95%","metric":"User Satisfaction","description":"Positive user feedback rating"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=1']
),
(
  '4aba644f-4d73-419f-b262-33bfefca5c9c',
  'Facility Equipment Configuration',
  'This project focused on creating an efficient system for administrators to set up facility management systems. The challenge was to create a flow that allows an administrator to set up required properties and determine what fields are configurable, resulting in equipment definitions that site managers can use to expedite installation without sacrificing flexibility.',
  'Iteros',
  ARRAY['Angular', 'TypeScript', 'Node.js', 'HTML', 'SCSS', 'Sketch'],
  ARRAY['Information Architecture', 'User Experience Design', 'Wireframing', 'Storyboarding', 'Interface Design', 'Software Development'],
  ARRAY['Determining minimum required information to start using the software', 'Balancing standardization with flexibility for different sites', 'Creating a consistent equipment setup process across multiple facilities', 'Designing a system that works for chains with similar equipment across locations', 'Developing a clear administrator workflow for equipment definition and configuration'],
  ARRAY['Collaborated with full development team to create a comprehensive flow diagram', 'Developed a library of equipment definitions for reuse across facilities', 'Implemented configurable property settings with administrator control', 'Created an intuitive interface for equipment setup and management', 'Designed a system that balances standardization with site-specific customization'],
  ARRAY['Information Architecture', 'UX Design', 'Interaction Design', 'User Research', 'Visual Design'],
  '[{"value":"Significantly improved","metric":"Setup Efficiency","description":"Streamlined the process of configuring equipment across multiple sites"},{"value":"Enhanced","metric":"Consistency","description":"Ensured consistent equipment installation across all facilities under a single customer"},{"value":"Customizable","metric":"Administrator Control","description":"Gave administrators precise control over which properties could be modified at the site level"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=200', 'https://picsum.photos/800/600?random=201']
),
(
  '550e8400-e29b-41d4-a716-446655440002',
  'Project Two',
  'An innovative mobile-first application that revolutionizes how users interact with digital content. Built with modern frameworks and featuring advanced user interface patterns and seamless responsive design.',
  'Tech Corp',
  ARRAY['React Native', 'TypeScript', 'Redux', 'API Integration'],
  ARRAY['Mobile Development', 'API Integration', 'User Testing'],
  ARRAY['Mobile performance optimization', 'Complex animations', 'Offline functionality'],
  ARRAY['Optimized rendering cycles', 'Used hardware acceleration', 'Implemented service workers'],
  ARRAY['Mobile Development', 'UX Design'],
  '[{"value":"300%","metric":"Download Rate","description":"Increase in app downloads"},{"value":"85%","metric":"Retention","description":"30-day user retention rate"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=2']
),
(
  'e628e5a7-1a1b-41e6-886b-94c43c2e3273',
  'My Portfolio Website',
  'A modern, responsive portfolio website built with React and Supabase. Features dynamic content management, project showcases, and admin panel for easy updates.',
  'Covington & Park Consulting',
  ARRAY['React', 'Supabase', 'SCSS', 'JavaScript'],
  ARRAY['Full-stack Development', 'UI/UX Design', 'Content Strategy'],
  ARRAY['Database Design', 'Admin Panel UX', 'Responsive Design'],
  ARRAY['Used Supabase for backend', 'Created intuitive admin interface', 'Mobile-first approach'],
  ARRAY['Web Development', 'Personal'],
  '[{"value":"< 2s","metric":"Load Time","description":"Fast loading performance"},{"value":"AA","metric":"Accessibility","description":"WCAG compliance achieved"}]'::jsonb,
  ARRAY['https://your-image-url.com/screenshot.png']
),
(
  '550e8400-e29b-41d4-a716-446655440003',
  'Project Three',
  'A data-driven analytics platform that provides real-time insights and comprehensive reporting capabilities. Features advanced data visualization, custom dashboards, and enterprise-grade security measures.',
  'Tech Corp',
  ARRAY['Python', 'React', 'D3.js', 'PostgreSQL', 'Docker'],
  ARRAY['Full-stack Development', 'Data Visualization', 'System Architecture'],
  ARRAY['Large dataset processing', 'Real-time updates', 'Security compliance'],
  ARRAY['Implemented data streaming', 'Used WebSocket connections', 'Added encryption layers'],
  ARRAY['Data Analytics', 'Full-stack'],
  '[{"value":"60%","metric":"Processing Speed","description":"Faster data processing time"},{"value":"99.9%","metric":"Accuracy","description":"Data accuracy improvement"},{"value":"120%","metric":"User Adoption","description":"Increase in active users"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=3']
),
(
  'feed8469-e2bc-4fc6-b207-9781bd15527d',
  'Energy Management Platform',
  'At Iteros, we developed an equipment-agnostic energy management system that allows for the creation of equipment definitions from which new equipment inherits properties. This enables consistent configuration in a fraction of the time compared to proprietary manufacturer software. The challenge was to create a modular interface that adapts to each facility''s unique configuration of assets without having to set up a custom dashboard for every customer.',
  'Iteros',
  ARRAY['Angular', 'TypeScript', 'Node.js', 'HTML', 'SCSS', 'Sketch'],
  ARRAY['User Research', 'Wireframing', 'Visual Design', 'Frontend Development', 'Information Architecture', 'User Experience Design', 'Interface Design'],
  ARRAY['Creating a system adaptable to diverse facility configurations', 'Designing for multiple user types with different goals', 'Developing a scalable interface for monitoring hundreds or thousands of sites', 'Identifying and displaying the most relevant metrics for different site types', 'Building a modular system that automatically adapts to available assets'],
  ARRAY['Developed detailed user personas to guide feature development', 'Created a widget-based system adaptable to different site types', 'Designed health indicators based on key performance metrics', 'Implemented a hierarchical navigation system for portfolios and sites', 'Developed site-type specific views (Monitoring, Consumer, Prosumer, Microgrid, etc.)'],
  ARRAY['Frontend Development', 'Data Visualization', 'UI Design', 'UX Design', 'Information Architecture'],
  '[{"value":"Significantly improved","metric":"Configuration Efficiency","description":"Reduced setup time through inheritance-based equipment definitions"},{"value":"Comprehensive","metric":"Monitoring Capability","description":"Created scalable system capable of monitoring thousands of sites"},{"value":"Enhanced","metric":"User Satisfaction","description":"Tailored interfaces for different user types based on specific goals"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=100', 'https://picsum.photos/800/600?random=101', 'http://127.0.0.1:54321/storage/v1/object/public/project-images/1764638474843_Screenshot_2024-05-14_at_1.51.46_PM.png']
),
(
  'c81edc23-5701-470f-b861-dcab5767e26f',
  'Product-Led Growth & Monetization Strategy: Revenue Through Customer Success',
  'Led comprehensive monetization and growth strategy transforming HiveWatch from early-stage customer acquisition to sustainable revenue growth. Achieved 65% increase in user engagement and subscription revenue through strategic premium feature development, pricing optimization, and customer success correlation analysis.',
  'HiveWatch',
  ARRAY['Analytics Platforms', 'A/B Testing Frameworks', 'Usage Tracking Systems', 'Guard Tours Mobile App', 'Twilio 911 Integration', 'Advanced Reporting', 'Customer Success Metrics', 'Revenue Analytics'],
  ARRAY['Monetization strategy framework development and value-based pricing optimization', 'Premium feature portfolio design including Guard Tours and Emergency 911 integration', 'Cross-functional revenue operations coordination across product, sales, and customer success', 'Customer success analytics and expansion opportunity identification', 'A/B testing and experimentation for feature adoption and pricing optimization', 'Usage analytics implementation tracking customer engagement and value realization', 'Sales enablement and competitive positioning for premium feature upselling', 'Customer lifecycle management and retention optimization strategies'],
  ARRAY['Developing monetization strategies without compromising customer satisfaction or platform value', 'Creating premium features that enhance rather than complicate existing security workflows', 'Balancing customer success with revenue growth across diverse enterprise customer segments', 'Establishing data-driven pricing models in competitive physical security market', 'Coordinating monetization initiatives across product, sales, and customer success teams', 'Measuring and optimizing customer lifetime value and expansion revenue opportunities', 'Differentiating premium capabilities against traditional PSIM vendors and emerging competitors'],
  ARRAY['Developed value-based pricing framework correlated with customer operational improvement', 'Created premium features solving specific customer pain points with clear ROI demonstration', 'Implemented comprehensive customer success analytics tracking engagement and satisfaction', 'Established systematic A/B testing for feature presentation and pricing optimization', 'Built cross-functional revenue operations ensuring alignment across customer-facing teams', 'Designed customer expansion methodology using usage data and success correlation', 'Created competitive differentiation through unique capabilities unavailable in traditional platforms'],
  ARRAY['Product-Led Growth', 'Monetization Strategy', 'Revenue Operations', 'Customer Success', 'Premium Features', 'Data-Driven Optimization'],
  '[{"value":"65% increase","metric":"User Engagement Growth","description":"Sustained growth in customer platform usage through strategic feature development"},{"value":"65% increase","metric":"Subscription Revenue Growth","description":"Direct revenue increase through premium feature upselling and customer expansion"},{"value":"70% improvement","metric":"Premium Feature Adoption","description":"Enhanced customer adoption of premium capabilities including Guard Tours and e911"},{"value":"85% increase","metric":"Customer Lifetime Value","description":"Improved retention and expansion revenue through value-driven feature development"},{"value":"75%","metric":"Upsell Success Rate","description":"High conversion from core platform to premium feature adoption"},{"value":"Average 300%","metric":"Customer ROI","description":"Quantified value realization through premium feature adoption and operational improvement"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=300', 'https://picsum.photos/800/600?random=301']
),
(
  '47411acb-e261-4c5f-bef1-1e2dddaf907a',
  'Lego Demo',
  'Energy management is abstract in nature, and therefore difficult to conceptualize without an applied demonstration. When our company wanted to demonstrate to potential investors how our software worked beyond screens, we developed a small-scale model using legos to show how our system balances and shares power, as well as integrates community renewables. The challenge was to augment this physical model with a conceptual digital overlay to visualize what was happening within the model.',
  'Iteros',
  ARRAY['Angular', 'TypeScript', 'HTML', 'Angular CLI', 'SCSS', 'D3', 'Adobe Illustrator'],
  ARRAY['Design', 'SVG Animation', 'Frontend Development', 'User Interface Engineering', 'Visual Conceptualization'],
  ARRAY['Making abstract energy concepts tangible and easy to understand', 'Creating a digital overlay that synchronized with physical model events', 'Visually representing complex energy flow concepts', 'Developing a demonstration system for investor presentations', 'Designing animations that accurately represented real energy behaviors'],
  ARRAY['Built a physical Lego model to demonstrate power sharing and balancing', 'Created isometric SVG models of physical components', 'Implemented animations to show energy flows and system states', 'Synchronized digital overlay with the physical model events', 'Designed visual changes to reflect concepts like cloudy weather affecting solar generation'],
  ARRAY['UI Design', 'UX Design', '3D Modeling', 'Data Visualization', 'Interactive Demo'],
  '[{"value":"Highly effective","metric":"Concept Communication","description":"Successfully demonstrated complex energy concepts to non-technical audiences"},{"value":"Featured","metric":"Investor Presentations","description":"Became a key demonstration tool during investor meetings"},{"value":"Showcased","metric":"Public Events","description":"Featured at the Sun Valley Forum in Idaho during a microgrid lab demonstration"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=400', 'https://picsum.photos/800/600?random=401']
),
(
  '803bb322-41a5-43c9-a50a-44b6017284e3',
  'Monitoring Lobby View',
  'Businesses want to put their energy efforts on display and need a type of view that is not only high-level, but also engaging. The challenge was to create a lobby view dashboard that is consistent with a business'' branding and relevant to their location.',
  'CleanSpark',
  ARRAY['SCALA', 'Play Framework', 'HTML', 'SCSS', 'Gulp.js', 'Photoshop'],
  ARRAY['Front-End Development', 'User Experience Design', 'Visual Design', 'Wireframing', 'Interface Design'],
  ARRAY['Creating visually engaging energy displays for public areas', 'Ensuring consistency with client branding', 'Developing displays relevant to each client''s specific location', 'Balancing customization with implementation efficiency'],
  ARRAY['Developed a flexible template-based design system', 'Created a standardized ''New Client Request Form'' for streamlined implementation', 'Balanced customized appearance with reusable components', 'Designed an efficient process for business development team to generate proposals'],
  ARRAY['Data Visualization', 'UI Design', 'UX Design', 'Process Optimization'],
  '[{"value":"Significantly improved","metric":"Implementation Efficiency","description":"Streamlined process allowed for much faster client implementations"},{"value":"Enhanced","metric":"Business Development","description":"Quick turnaround time for new client proposals"},{"value":"High","metric":"Client Satisfaction","description":"Clients received personalized-looking displays that matched their branding"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=500', 'https://picsum.photos/800/600?random=501']
),
(
  '4f6bd890-0dd6-42f4-8b86-ad70bed84572',
  'Savings Playground',
  'When a customer wants to know how to optimally reduce their energy consumption or overall energy costs, many factors need to be considered. Companies that provide these types of reports spend a lot of time sending an engineer to collect data, then manually entering this data and tweaking parameters to arrive at potential options. Our company wanted to streamline this process and account for everything down to tax credits to provide a highly accurate report.',
  'CleanSpark',
  ARRAY['AngularJS', 'HTML', 'SCSS', 'Gulp.js', 'Sketch', 'Whiteboarding'],
  ARRAY['Front-End Development', 'Information Architecture', 'User Experience Design', 'Interaction Design', 'Wireframe Prototyping', 'Multi-platform Interface Design'],
  ARRAY['Converting a complex MATLAB tool into user-friendly interfaces', 'Creating versions for multiple platforms (tablet, mobile, web, lead generator)', 'Simplifying complex financial and energy data for various user types', 'Organizing a complex multi-step process into a coherent flow', 'Managing conditional inputs and dependent configuration options'],
  ARRAY['Conducted detailed workflow analysis with the engineer who created the original tool', 'Used physical card sorting to re-organize interface components', 'Created a four-step process to simplify the perceived complexity', 'Implemented modal popups for complex configuration options', 'Developed responsive designs for various platforms (tablet, mobile, web)', 'Created a simplified one-page lead generator for sales teams'],
  ARRAY['Information Architecture', 'UX Design', 'UI Design', 'Wireframing', 'Responsive Design'],
  '[{"value":"Significantly improved","metric":"Engineer Efficiency","description":"Streamlined on-site data collection process"},{"value":"Multi-platform","metric":"Tool Adoption","description":"Successfully deployed across tablet, mobile, and web platforms"},{"value":"Company-wide","metric":"Internal Usage","description":"Tool became a standard internal resource with potential as a licensed revenue stream"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=600', 'https://picsum.photos/800/600?random=601']
),
(
  '32acc26c-d905-4369-be07-012e122c3e19',
  'Platform Integration Leadership: IoT Capabilities Across ServiceNow Ecosystem',
  'Led comprehensive platform integration strategy transforming Connected Operations from standalone IoT product into ecosystem-enhancing capability across ServiceNow''s product portfolio. Partnered with Design & Experience Organization and multiple product teams to create seamless integration enhancing CSM, FSM, and ITAM without disrupting existing workflows.',
  'ServiceNow',
  ARRAY['ServiceNow Platform APIs', 'Component Library Architecture', 'Design System Integration', 'Multi-Product Integration', 'CSM/FSM/ITAM Platforms', 'RESTful API Design', 'UI Component Standardization'],
  ARRAY['Cross-product integration strategy spanning Connected Operations, CSM, FSM, and ITAM teams', 'Design & Experience Organization partnership on reusable IoT component development', 'API-first integration architecture enabling seamless platform enhancement', 'Customer experience consistency across enhanced ServiceNow products', 'Technical architecture alignment for IoT capability integration', 'Go-to-market coordination ensuring ''Better Together'' value proposition', 'Performance optimization maintaining platform speed and reliability', 'Component library development for reusable IoT visualization elements'],
  ARRAY['Integrating new IoT capabilities across established products without workflow disruption', 'Coordinating multiple product organizations with different roadmaps and priorities', 'Maintaining ServiceNow design system consistency while adding innovative IoT features', 'Ensuring integration performance didn''t impact existing product functionality', 'Creating cohesive customer experience across multiple enhanced products', 'Managing technical dependencies across complex platform architecture', 'Balancing innovation with platform stability and customer satisfaction'],
  ARRAY['Developed progressive integration approach with phased IoT capability rollout', 'Established regular cross-product planning sessions and dependency management', 'Created reusable IoT components adopted into ServiceNow enterprise design system', 'Implemented comprehensive performance monitoring and optimization protocols', 'Designed API-first integration minimizing disruption to existing workflows', 'Built systematic testing frameworks ensuring integration quality and reliability', 'Created customer communication strategy positioning enhancements as natural evolution'],
  ARRAY['Platform Integration', 'Design System Leadership', 'Cross-Product Coordination', 'API Architecture', 'Customer Experience', 'Component Development'],
  '[{"value":"3 major products","metric":"Product Enhancement","description":"Successfully enhanced CSM, FSM, and ITAM with integrated IoT capabilities"},{"value":"Multiple components","metric":"Design System Adoption","description":"IoT visualization components adopted into ServiceNow''s enterprise design system"},{"value":"99.9%+ uptime","metric":"Performance Preservation","description":"Maintained platform performance standards while adding new capabilities"},{"value":"Zero workflow disruption","metric":"Customer Experience","description":"Enhanced products without requiring customer retraining or process changes"},{"value":"Seamless connectivity","metric":"Integration Success","description":"API-first architecture enabling smooth integration across ServiceNow platform"},{"value":"45+ contributors","metric":"Cross-Team Coordination","description":"Successfully coordinated integration across multiple product organizations"}]'::jsonb,
  ARRAY['https://picsum.photos/800/600?random=700', 'https://picsum.photos/800/600?random=701']
);

-- Insert project sections
INSERT INTO project_sections (project_id, section_order, header, type, images, captions, text_content, gif_url, video_url) VALUES 
(
  '32acc26c-d905-4369-be07-012e122c3e19',
  1,
  'Project Overview',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=700'],
  ARRAY['ServiceNow Platform Integration Architecture - IoT capabilities seamlessly integrated across CSM, FSM, and ITAM products'],
  'Led comprehensive platform integration strategy transforming Connected Operations from a standalone IoT product into ecosystem-enhancing capabilities across ServiceNow''s product portfolio. The initiative required partnering with the Design & Experience Organization and multiple product teams to create seamless integration that enhanced CSM, FSM, and ITAM without disrupting existing customer workflows.',
  NULL,
  NULL
),
(
  '32acc26c-d905-4369-be07-012e122c3e19',
  2,
  'Cross-Product Integration Strategy',
  'text',
  NULL,
  NULL,
  'The integration strategy spanned multiple product organizations with different roadmaps and priorities. I established regular cross-product planning sessions and dependency management processes to ensure coordinated development. The approach balanced innovation with platform stability while maintaining ServiceNow design system consistency across all enhanced products.',
  NULL,
  NULL
),
(
  '32acc26c-d905-4369-be07-012e122c3e19',
  3,
  'Design System Leadership',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=702'],
  ARRAY['Design System Component Library - Reusable IoT visualization components adopted into ServiceNow design system'],
  'Partnered with the Design & Experience Organization to develop reusable IoT components that were adopted into ServiceNow''s enterprise design system. This collaboration ensured consistent user experience across all enhanced products while providing scalable visualization elements for IoT data integration.',
  NULL,
  NULL
),
(
  '32acc26c-d905-4369-be07-012e122c3e19',
  4,
  'API-First Architecture',
  'text',
  NULL,
  NULL,
  'Designed an API-first integration architecture that enabled seamless platform enhancement while minimizing disruption to existing workflows. This approach allowed IoT capabilities to be integrated across Connected Operations, CSM, FSM, and ITAM platforms while maintaining the high performance standards and reliability that ServiceNow customers expect.',
  NULL,
  NULL
),
(
  '32acc26c-d905-4369-be07-012e122c3e19',
  5,
  'Enhanced Product Workflows',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=703'],
  ARRAY['Enhanced Product Workflows - IoT data seamlessly integrated into existing CSM, FSM, and ITAM workflows'],
  'The integration successfully enhanced three major ServiceNow products with IoT capabilities while preserving 99.9%+ uptime and ensuring zero workflow disruption for customers. The seamless connectivity enabled by the API-first architecture meant customers experienced enhanced functionality as a natural platform evolution rather than disruptive changes.',
  NULL,
  NULL
),
(
  '32acc26c-d905-4369-be07-012e122c3e19',
  6,
  'Key Achievements & Impact',
  'text',
  NULL,
  NULL,
  'Successfully coordinated integration across 45+ contributors from multiple product organizations, resulting in IoT visualization components being adopted into ServiceNow''s enterprise design system. The project maintained platform performance standards while adding innovative capabilities, creating a ''Better Together'' value proposition that enhanced customer experience without requiring retraining or process changes.',
  NULL,
  NULL
),
(
  '47411acb-e261-4c5f-bef1-1e2dddaf907a',
  1,
  'Project Overview',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=400'],
  ARRAY['Lego Microgrid Demo Overview - Overview of the physical Lego model with digital overlay'],
  'Energy management concepts are inherently abstract and difficult to conceptualize without applied demonstration. To help potential investors understand how our software worked beyond screens, we developed a small-scale Lego model that demonstrated power sharing, balancing, and community renewable integration with a synchronized digital overlay.',
  NULL,
  NULL
),
(
  '47411acb-e261-4c5f-bef1-1e2dddaf907a',
  2,
  'Physical Model Development',
  'images',
  ARRAY['https://picsum.photos/800/600?random=402', 'https://picsum.photos/800/600?random=403'],
  ARRAY['The physical setup of the Lego demonstration', 'Initial concept planning on whiteboard'],
  NULL,
  NULL,
  NULL
),
(
  '47411acb-e261-4c5f-bef1-1e2dddaf907a',
  3,
  'Digital Interface Design',
  'images',
  ARRAY['https://picsum.photos/800/600?random=404', 'https://picsum.photos/800/600?random=405'],
  ARRAY['Digital mockup of the interface', 'Refined SVG models of the physical components in isometric view'],
  NULL,
  NULL,
  NULL
),
(
  '47411acb-e261-4c5f-bef1-1e2dddaf907a',
  4,
  'Animation & Synchronization',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=406'],
  ARRAY['Animated SVG components showing energy flow changes'],
  'The digital overlay featured synchronized animations that responded to physical model events. Visual changes reflected real energy concepts, such as cloudy weather affecting solar generation, power flows between buildings, and energy storage charging and discharging cycles. The animations helped make abstract energy management concepts tangible and understandable.',
  NULL,
  NULL
),
(
  '47411acb-e261-4c5f-bef1-1e2dddaf907a',
  5,
  'Demonstration Impact',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=407'],
  ARRAY['The microgrid demonstration at the Sun Valley Forum in Idaho'],
  'The Lego demonstration became a powerful communication tool that effectively conveyed complex energy management concepts to non-technical audiences. It served as a featured element in investor presentations and was showcased at public events, including the Sun Valley Forum in Idaho during a microgrid lab demonstration.',
  NULL,
  NULL
),
(
  '47411acb-e261-4c5f-bef1-1e2dddaf907a',
  6,
  'Technical Implementation',
  'text',
  NULL,
  NULL,
  'The project utilized Angular and TypeScript for the digital interface, D3 for data visualization, and Adobe Illustrator for creating precise isometric SVG models. The challenge was synchronizing the digital overlay with physical model events while maintaining smooth animations that accurately represented real energy behaviors and system states.',
  NULL,
  NULL
),
(
  '4aba644f-4d73-419f-b262-33bfefca5c9c',
  1,
  'Project Overview',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=200'],
  ARRAY['Equipment Configuration Flow Diagram - Process flow for equipment configuration'],
  'The Facility Equipment Configuration project aimed to revolutionize how administrators set up and manage facility equipment across multiple sites. By creating a system that allows for standardized equipment definitions while maintaining flexibility for site-specific needs, we enabled faster deployment and more consistent installations.',
  NULL,
  NULL
),
(
  '4aba644f-4d73-419f-b262-33bfefca5c9c',
  2,
  'Design Process & Flow Development',
  'images',
  ARRAY['https://picsum.photos/800/600?random=202', 'https://picsum.photos/800/600?random=203'],
  ARRAY['First iteration of the equipment configuration flow', 'Second iteration with refined user pathways'],
  NULL,
  NULL,
  NULL
),
(
  '4aba644f-4d73-419f-b262-33bfefca5c9c',
  3,
  'Information Architecture Challenge',
  'text',
  NULL,
  NULL,
  'The core challenge was determining the minimum required information needed to start using the software effectively. We had to balance the need for comprehensive equipment data with the desire for quick setup. Through user research and iterative design, we identified the critical data points and created a progressive disclosure system that allowed administrators to add detail as needed without being overwhelmed initially.',
  NULL,
  NULL
),
(
  '4aba644f-4d73-419f-b262-33bfefca5c9c',
  4,
  'Equipment Definition System',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=204'],
  ARRAY['Implementation showing details of a new equipment definition'],
  'The equipment definition system became the cornerstone of our solution. Administrators could create master equipment definitions that served as templates, specifying which properties were required and which could be customized at the site level. This approach provided consistency across facilities while allowing for necessary flexibility.',
  NULL,
  NULL
),
(
  '4aba644f-4d73-419f-b262-33bfefca5c9c',
  5,
  'Implementation & User Workflow',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=205', 'https://picsum.photos/800/600?random=206'],
  ARRAY['Adding equipment using a pre-defined template', 'Viewing and managing equipment details after addition'],
  'The final implementation featured an intuitive workflow where site managers could quickly add equipment using pre-defined templates. The system automatically inherited properties from the equipment definition, while still allowing for site-specific customizations where permitted by the administrator. This dramatically reduced setup time and errors.',
  NULL,
  NULL
),
(
  '4aba644f-4d73-419f-b262-33bfefca5c9c',
  6,
  'Key Outcomes & Impact',
  'text',
  NULL,
  NULL,
  'The Facility Equipment Configuration system successfully streamlined equipment setup across multiple sites, ensuring consistency while maintaining necessary flexibility. Administrator control over configurable properties meant that corporate standards could be enforced while still allowing for site-specific needs. The library of reusable equipment definitions significantly reduced setup time for new facilities, particularly benefiting chains with similar equipment across locations.',
  NULL,
  NULL
),
(
  '4f6bd890-0dd6-42f4-8b86-ad70bed84572',
  1,
  'Project Overview',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=600'],
  ARRAY['Savings Playground Overview - Main view of the energy savings calculation tool'],
  'The Savings Playground project transformed a complex MATLAB tool into user-friendly interfaces for calculating optimal energy cost reduction strategies. The challenge involved streamlining a process that previously required engineers to manually collect data and tweak parameters, accounting for everything from energy consumption to tax credits for highly accurate reports.',
  NULL,
  NULL
),
(
  '4f6bd890-0dd6-42f4-8b86-ad70bed84572',
  2,
  'Original Tool Analysis',
  'images',
  ARRAY['https://picsum.photos/800/600?random=602', 'https://picsum.photos/800/600?random=603'],
  ARRAY['The original MATLAB tool used for calculations', 'Process of breaking down the tool into components for reorganization'],
  NULL,
  NULL,
  NULL
),
(
  '4f6bd890-0dd6-42f4-8b86-ad70bed84572',
  3,
  'Information Architecture Process',
  'text',
  NULL,
  NULL,
  'I conducted detailed workflow analysis with the engineer who created the original MATLAB tool, then used physical card sorting to re-organize interface components. This process revealed opportunities to simplify the perceived complexity by creating a structured four-step process that made the tool more accessible to various user types.',
  NULL,
  NULL
),
(
  '4f6bd890-0dd6-42f4-8b86-ad70bed84572',
  4,
  'Design Development',
  'images',
  ARRAY['https://picsum.photos/800/600?random=604', 'https://picsum.photos/800/600?random=605', 'https://picsum.photos/800/600?random=606'],
  ARRAY['Initial wireframe showing reorganized process flow', 'Detailed wireframe with interface elements', 'Modal design for managing complex configuration options'],
  NULL,
  NULL,
  NULL
),
(
  '4f6bd890-0dd6-42f4-8b86-ad70bed84572',
  5,
  'Multi-Platform Implementation',
  'images',
  ARRAY['https://picsum.photos/800/600?random=607', 'https://picsum.photos/800/600?random=608', 'https://picsum.photos/800/600?random=609', 'https://picsum.photos/800/600?random=610'],
  ARRAY['Desktop version themed for a partnering solar company', 'Simplified lead generator version requested by the sales team', 'iPad version for engineers to use while surveying on site', 'Android mobile version of the tool'],
  NULL,
  NULL,
  NULL
),
(
  '4f6bd890-0dd6-42f4-8b86-ad70bed84572',
  6,
  'Impact & Results',
  'text',
  NULL,
  NULL,
  'The Savings Playground significantly improved engineer efficiency by streamlining the on-site data collection process. The tool was successfully deployed across tablet, mobile, and web platforms, becoming a company-wide standard internal resource with potential as a licensed revenue stream. The multi-platform approach ensured accessibility for various use cases and user types.',
  NULL,
  NULL
),
(
  '550e8400-e29b-41d4-a716-446655440001',
  1,
  'Project Images',
  'images',
  ARRAY['https://picsum.photos/800/600?random=20', 'https://picsum.photos/800/600?random=21'],
  ARRAY['Main interface screenshot', 'Mobile responsive design'],
  NULL,
  NULL,
  NULL
),
(
  '550e8400-e29b-41d4-a716-446655440001',
  2,
  'Technical Implementation',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=22'],
  ARRAY['Architecture diagram'],
  'The technical implementation focuses on modern React patterns with TypeScript for type safety. We implemented a modular architecture that allows for easy scaling and maintenance. The component structure follows atomic design principles, ensuring reusability and consistency across the application.',
  NULL,
  NULL
),
(
  '550e8400-e29b-41d4-a716-446655440001',
  3,
  'Performance Metrics',
  'text',
  NULL,
  NULL,
  'After implementing the optimizations, we achieved significant performance improvements. Load time decreased by 40%, user satisfaction increased to 95%, and the application now handles 3x more concurrent users. These metrics were measured over a 3-month period with consistent monitoring.',
  NULL,
  NULL
),
(
  '550e8400-e29b-41d4-a716-446655440002',
  1,
  'Mobile Interface Design',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=30', 'https://picsum.photos/800/600?random=31'],
  ARRAY['Home screen design', 'Navigation flow'],
  'The mobile interface was designed with a mobile-first approach, ensuring optimal user experience across all device sizes. We implemented intuitive gesture-based navigation and smooth animations to create a seamless user journey.',
  NULL,
  NULL
),
(
  '550e8400-e29b-41d4-a716-446655440002',
  2,
  'User Testing Results',
  'text',
  NULL,
  NULL,
  'Extensive user testing revealed key insights that shaped the final product. We conducted usability sessions with 50+ users across different demographics, leading to significant improvements in navigation patterns and content hierarchy. The iterative testing process resulted in a 300% increase in user engagement.',
  NULL,
  NULL
),
(
  '550e8400-e29b-41d4-a716-446655440003',
  1,
  'Dashboard Overview',
  'images',
  ARRAY['https://picsum.photos/800/600?random=40', 'https://picsum.photos/800/600?random=41', 'https://picsum.photos/800/600?random=42'],
  ARRAY['Main dashboard', 'Analytics view', 'Reporting interface'],
  NULL,
  NULL,
  NULL
),
(
  '550e8400-e29b-41d4-a716-446655440003',
  2,
  'Data Visualization Features',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=43'],
  ARRAY['Interactive charts and graphs'],
  'Advanced data visualization capabilities allow users to explore complex datasets through interactive charts, real-time updates, and customizable dashboards. The platform supports multiple chart types including heat maps, scatter plots, and time-series visualizations with drill-down functionality.',
  NULL,
  NULL
),
(
  '803bb322-41a5-43c9-a50a-44b6017284e3',
  1,
  'Project Overview',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=500'],
  ARRAY['Lobby Dashboard Overview - Main dashboard view for energy monitoring'],
  'Businesses wanted to showcase their energy efforts in public spaces through engaging, high-level displays. The challenge was creating lobby view dashboards that maintained consistency with each business''s branding while remaining relevant to their specific location and energy initiatives.',
  NULL,
  NULL
),
(
  '803bb322-41a5-43c9-a50a-44b6017284e3',
  2,
  'Design Evolution',
  'images',
  ARRAY['https://picsum.photos/800/600?random=502', 'https://picsum.photos/800/600?random=503'],
  ARRAY['The original dashboard design', 'The improved dashboard design'],
  NULL,
  NULL,
  NULL
),
(
  '803bb322-41a5-43c9-a50a-44b6017284e3',
  3,
  'Process Optimization',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=504'],
  ARRAY['Client Request Form - Form created to streamline the dashboard creation process'],
  'To address the challenge of balancing customization with implementation efficiency, I developed a standardized ''New Client Request Form'' that streamlined the entire process. This form allowed the business development team to quickly gather requirements and generate proposals while ensuring each client received a personalized dashboard experience.',
  NULL,
  NULL
),
(
  '803bb322-41a5-43c9-a50a-44b6017284e3',
  4,
  'Template-Based Design System',
  'text',
  NULL,
  NULL,
  'The solution involved creating a flexible template-based design system that balanced customized appearance with reusable components. This approach allowed for rapid deployment of client-specific dashboards while maintaining consistent quality and reducing development time.',
  NULL,
  NULL
),
(
  '803bb322-41a5-43c9-a50a-44b6017284e3',
  5,
  'Client Implementation Examples',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=505'],
  ARRAY['Multiple Dashboard Examples - Various client dashboard implementations'],
  'The template system enabled creation of multiple client-specific implementations, each reflecting the unique branding and location-specific energy data of different businesses. The standardized process significantly improved implementation efficiency while maintaining high client satisfaction.',
  NULL,
  NULL
),
(
  '803bb322-41a5-43c9-a50a-44b6017284e3',
  6,
  'Key Outcomes',
  'text',
  NULL,
  NULL,
  'The project successfully streamlined the client implementation process, allowing for much faster turnaround times and enhanced business development capabilities. Clients received personalized-looking displays that perfectly matched their branding requirements while showcasing their energy initiatives effectively in public spaces.',
  NULL,
  NULL
),
(
  'c81edc23-5701-470f-b861-dcab5767e26f',
  1,
  'Project Overview',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=300'],
  ARRAY['Product-Led Growth Monetization Framework - Value-driven pricing and premium feature development supporting customer success'],
  'Led comprehensive monetization and growth strategy at HiveWatch, transforming the company from early-stage customer acquisition to sustainable revenue growth. Through strategic premium feature development, pricing optimization, and customer success correlation analysis, achieved significant improvements in user engagement and subscription revenue.',
  NULL,
  NULL
),
(
  'c81edc23-5701-470f-b861-dcab5767e26f',
  2,
  'Premium Feature Portfolio Development',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=302'],
  ARRAY['Premium Feature Portfolio - Guard Tours, Emergency 911, and Advanced Analytics driving customer expansion'],
  'Designed and developed a comprehensive premium feature portfolio including Guard Tours mobile app functionality, Twilio 911 integration, and advanced reporting capabilities. Each feature was designed to solve specific customer pain points while demonstrating clear ROI and value realization.',
  NULL,
  NULL
),
(
  'c81edc23-5701-470f-b861-dcab5767e26f',
  3,
  'Monetization Strategy Framework',
  'text',
  NULL,
  NULL,
  'Developed a value-based pricing framework directly correlated with customer operational improvement. This approach ensured that monetization strategies enhanced rather than compromised customer satisfaction, creating a sustainable growth model that balanced revenue objectives with customer success across diverse enterprise segments.',
  NULL,
  NULL
),
(
  'c81edc23-5701-470f-b861-dcab5767e26f',
  4,
  'Data-Driven Optimization',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=303'],
  ARRAY['Revenue Growth Analytics - Customer success correlation and expansion revenue tracking dashboard'],
  'Implemented comprehensive customer success analytics and systematic A/B testing frameworks to optimize feature adoption and pricing strategies. The data-driven approach enabled precise measurement of customer lifetime value, expansion revenue opportunities, and competitive differentiation against traditional PSIM vendors.',
  NULL,
  NULL
),
(
  'c81edc23-5701-470f-b861-dcab5767e26f',
  5,
  'Cross-Functional Revenue Operations',
  'text',
  NULL,
  NULL,
  'Built cross-functional revenue operations ensuring alignment across product, sales, and customer success teams. This coordination was essential for successful monetization initiatives, enabling seamless customer expansion methodology and effective sales enablement for premium feature upselling.',
  NULL,
  NULL
),
(
  'c81edc23-5701-470f-b861-dcab5767e26f',
  6,
  'Key Outcomes & Impact',
  'text',
  NULL,
  NULL,
  'Achieved remarkable results including 65% increases in both user engagement and subscription revenue, 70% improvement in premium feature adoption, 85% increase in customer lifetime value, and 75% upsell success rate. Customer ROI averaged 300% through premium feature adoption and operational improvements, validating the value-driven monetization approach.',
  NULL,
  NULL
),
(
  'feed8469-e2bc-4fc6-b207-9781bd15527d',
  1,
  'Project Overview',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=100'],
  ARRAY['Energy Management Platform Overview - Main view of the platform dashboard'],
  'The Energy Management Platform was designed to provide a comprehensive, equipment-agnostic solution for energy monitoring and management. The interface adapts to each facility''s unique configuration, eliminating the need for custom dashboards for every customer.',
  NULL,
  NULL
),
(
  'feed8469-e2bc-4fc6-b207-9781bd15527d',
  2,
  'User Research & Personas',
  'images',
  ARRAY['https://picsum.photos/800/600?random=102', 'https://picsum.photos/800/600?random=103'],
  ARRAY['Analysis of different user types and their goals', 'Detailed personas developed to guide design decisions'],
  NULL,
  NULL,
  NULL
),
(
  'feed8469-e2bc-4fc6-b207-9781bd15527d',
  3,
  'Design Process',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=104', 'https://picsum.photos/800/600?random=105'],
  ARRAY['Initial dashboard design for monitoring site', 'Early design concepts and wireframes for the platform'],
  'The design process began with understanding user needs and iterating on dashboard concepts. We moved from basic monitoring displays to a sophisticated widget-based system that could adapt to different facility types and user requirements.',
  NULL,
  NULL
),
(
  'feed8469-e2bc-4fc6-b207-9781bd15527d',
  4,
  'Widget System & Modular Interface',
  'image_text',
  ARRAY['https://picsum.photos/800/600?random=106'],
  ARRAY['Modular widgets designed for different site types'],
  'The widget system was a key innovation, allowing the interface to automatically adapt based on available assets and facility type. Each widget was designed to display relevant metrics for specific equipment types, ensuring users see the most important information for their context.',
  NULL,
  NULL
),
(
  'feed8469-e2bc-4fc6-b207-9781bd15527d',
  5,
  'Portfolio & Site Management',
  'images',
  ARRAY['https://picsum.photos/800/600?random=107', 'https://picsum.photos/800/600?random=108', 'https://picsum.photos/800/600?random=109'],
  ARRAY['High-level view of multiple sites in portfolio', 'Detailed information for a specific site', 'Interface showing site health based on power usage and cost'],
  NULL,
  NULL,
  NULL
),
(
  'feed8469-e2bc-4fc6-b207-9781bd15527d',
  6,
  'Key Outcomes',
  'text',
  NULL,
  NULL,
  'The Energy Management Platform successfully reduced configuration time through inheritance-based equipment definitions, created a scalable system capable of monitoring thousands of sites, and enhanced user satisfaction by tailoring interfaces to different user types based on their specific goals. The modular approach allowed for rapid deployment across diverse facility types without custom development.',
  NULL,
  NULL
);